# Generated by Django 6.0.4 on 2026-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('socio', 'Sócio'), ('analista', 'Analista'), ('gestor', 'Gestor'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
