services:
  - type: web
    name: axia-projeto
    runtime: python
    pythonVersion: "3.14"
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input
    startCommand: gunicorn axia.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.14"
    plan: starter
    maxInstanceCount: 1
