# Generated by Django 6.0.4 on 2026-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('vencido', 'Vencido'), ('registrado', 'Registrado'), ('protocolado', 'Protocolado')], default='Pendente', max_length=50),
        ),
    ]
