# Generated by Django 6.0.4 on 2026-04-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leiloes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Rua/Avenida')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apto', 'Apartamento'), ('terreno', 'Terreno'), ('comercial', 'Ponto Comercial')], max_length=20)),
                ('area', models.FloatField()),
                ('estado_conservacao', models.CharField(max_length=50, verbose_name='Estado de Conservação')),
                ('situacao_juridica', models.CharField(max_length=100, verbose_name='Situação Jurídica')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leiloes.leilao')),
            ],
        ),
    ]
