# Generated by Django 6.0.4 on 2026-04-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
