# Generated by Django 6.0.4 on 2026-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_latitude_imovel_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area',
            field=models.FloatField(help_text='Área do imóvel em metros quadrados', verbose_name='Área em m²'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='estado_conservacao',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('regular', 'Regular'), ('bom', 'Bom'), ('otimo', 'Ótimo'), ('novo', 'Novo'), ('demolido', 'Demolido')], help_text='Estado de conservação do imóvel', max_length=50, verbose_name='Estado de Conservação'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=models.CharField(help_text='Número da matrícula do imóvel no cartório de registro de imóveis', max_length=100, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='situacao_juridica',
            field=models.CharField(choices=[('Alineação', 'Alienação'), ('Penhora', 'Penhora'), ('inventário', 'Inventário'), ('usucapião', 'Usucapião'), ('hipoteca', 'Hipoteca'), ('outros', 'Outros')], help_text='Situação jurídica do imóvel', max_length=50, verbose_name='Situação Jurídica'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('apto', 'Apartamento'), ('terreno', 'Terreno'), ('comercial', 'Ponto Comercial')], help_text='Tipo do imóvel (casa, apartamento, terreno, ponto comercial)', max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
