# Generated by Django 6.0.4 on 2026-04-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_imovel_options_alter_imovel_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
