# Generated by Django 6.0.4 on 2026-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_alter_imovel_latitude_alter_imovel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='image_imovel',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis/', verbose_name='Imagem do Imóvel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='situacao_juridica',
            field=models.CharField(choices=[('alineação', 'Alienação'), ('penhora', 'Penhora'), ('inventário', 'Inventário'), ('usucapião', 'Usucapião'), ('hipoteca', 'Hipoteca'), ('outros', 'Outros')], help_text='Situação jurídica do imóvel', max_length=50, verbose_name='Situação Jurídica'),
        ),
    ]
