# Generated by Django 6.0.4 on 2026-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_imovel_image_imovel_imovel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='situacao_juridica',
            field=models.CharField(choices=[('alienacao', 'Alienação'), ('penhora', 'Penhora'), ('inventário', 'Inventário'), ('usucapiao', 'Usucapião'), ('hipoteca', 'Hipoteca'), ('outros', 'Outros')], help_text='Situação jurídica do imóvel', max_length=50, verbose_name='Situação Jurídica'),
        ),
    ]
