# Generated by Django 6.0.4 on 2026-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='tipo',
            field=models.CharField(choices=[('venda', 'Venda'), ('locacao', 'Locação')], default='venda', max_length=20),
        ),
    ]
