# Generated by Django 6.0.4 on 2026-04-27 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0001_initial'),
        ('imoveis', '0004_alter_imovel_latitude_alter_imovel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custoaquisicao',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='custoaquisicao',
            name='tipo',
            field=models.CharField(choices=[('taxas_cartorio', 'Taxas de Cartório'), ('impostos', 'Impostos'), ('honorarios_advogado', 'Honorários de Advogado'), ('despesas_viagem', 'Despesas de Viagem'), ('outros', 'Outros')], max_length=100, verbose_name='Tipo de Custo'),
        ),
        migrations.AlterField(
            model_name='custoaquisicao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='custoreforma',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='custoreforma',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='custoreforma',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='custoreforma',
            name='valor_previsto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Previsto'),
        ),
        migrations.AlterField(
            model_name='custoreforma',
            name='valor_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Real'),
        ),
        migrations.CreateModel(
            name='CustoHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Condominio', 'Condomínio'), ('IPTU', 'IPTU'), ('Seguro', 'Seguro'), ('Utilidades', 'Água/Luz'), ('Outros', 'Outros')], max_length=100, verbose_name='Tipo de Custo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('recorrente', models.BooleanField(default=True, verbose_name='Recorrente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
            ],
        ),
    ]
