# Generated by Django 6.0.4 on 2026-04-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0002_alter_custoaquisicao_data_alter_custoaquisicao_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custoholding',
            name='recorrente',
        ),
        migrations.RemoveField(
            model_name='custoholding',
            name='valor',
        ),
        migrations.AddField(
            model_name='custoholding',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custoholding',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custoholding',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='custoholding',
            name='tipo',
            field=models.CharField(choices=[('Condominio', 'Condomínio'), ('IPTU', 'IPTU'), ('Seguro', 'Seguro'), ('Utilidades', 'Água/Luz'), ('Outros', 'Outros')], max_length=100),
        ),
    ]
