# Generated by Django 6.0.4 on 2026-04-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0003_remove_custoholding_recorrente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custoaquisicao',
            options={'verbose_name': 'Custo de Aquisição', 'verbose_name_plural': 'Custos de Aquisição'},
        ),
        migrations.AlterModelOptions(
            name='custoholding',
            options={'verbose_name': 'Custo de Holding', 'verbose_name_plural': 'Custos de Holding'},
        ),
        migrations.AlterModelOptions(
            name='custoreforma',
            options={'verbose_name': 'Custo de Reforma', 'verbose_name_plural': 'Custos de Reforma'},
        ),
    ]
