# Generated by Django 6.0.4 on 2026-04-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=100)),
                ('comarca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('data_leilao', models.DateTimeField()),
                ('valor_avaliacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('link_edital', models.URLField()),
            ],
        ),
    ]
