# Generated by Django 6.0.4 on 2026-04-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='forma',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='online', help_text='Indica se o leilão é presencial ou online', max_length=20, verbose_name='Forma de Realização'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='comarca',
            field=models.CharField(max_length=100, verbose_name='Comarca'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='processo',
            field=models.CharField(max_length=100, verbose_name='Processo'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='tipo',
            field=models.CharField(choices=[('judicial', 'Judicial'), ('extrajudicial', 'Extrajudicial')], default='judicial', help_text='Indica se o leilão é judicial ou extrajudicial', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='valor_avaliacao',
            field=models.DecimalField(decimal_places=2, help_text='Valor de avaliação do imóvel', max_digits=12),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, help_text='Valor mínimo do leilão', max_digits=12),
        ),
    ]
