# Generated by Django 6.0.4 on 2026-04-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0002_leilao_forma_alter_leilao_comarca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='condicoes_pagamento',
            field=models.TextField(default=2, help_text='Condições de pagamento do leilão', verbose_name='Condições de pagamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leilao',
            name='forma',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], default='online', help_text='Indica se o leilão é presencial, online ou híbrido', max_length=20, verbose_name='Forma de Realização'),
        ),
    ]
