# Generated by Django 6.0.4 on 2026-04-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0003_leilao_condicoes_pagamento_alter_leilao_forma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='condicoes_pagamento',
            field=models.TextField(help_text='Condições de pagamento do leilão', max_length=255, verbose_name='Condições de pagamento'),
        ),
    ]
