# Generated by Django 6.0.4 on 2026-04-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0004_alter_leilao_condicoes_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='comarca',
            field=models.CharField(help_text='Nome da comarca onde o leilão será realizado', max_length=100, verbose_name='Comarca'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='processo',
            field=models.CharField(help_text='Número do processo judicial ou extrajudicial', max_length=100, verbose_name='Processo'),
        ),
    ]
