# Generated by Django 6.0.4 on 2026-04-27 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0005_alter_leilao_comarca_alter_leilao_processo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leilao',
            options={'verbose_name': 'Leilão', 'verbose_name_plural': 'Leilões'},
        ),
    ]
