# Generated by Django 6.0.4 on 2026-04-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0006_alter_leilao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='comarca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='condicoes_pagamento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='data_leilao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='forma',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='link_edital',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='processo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='tipo',
            field=models.CharField(choices=[('judicial', 'Judicial'), ('extrajudicial', 'Extrajudicial')], default='judicial', max_length=20),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='valor_avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='valor_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
